[package]
name = "cacao"
version = "0.1.0"
authors = ["Spruce Systems, Inc."]
edition = "2021"
license = "Apache-2.0"
description = "Core library for CACAO traits and data structures"
repository = "https://github.com/spruceid/cacao/"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
eip4361 = ["siwe", "hex"]
default = ["eip4361"]

[dependencies]
siwe = { version = "0.1", optional = true }
iri-string = { version = "0.4", features = ["serde", "serde-std"] }
chrono = "0.4"
thiserror = "1.0"
url = "2.2"
async-trait = "0.1"
serde = "1.0"
serde_with = "1.11"
http = "0.2.5"
hex = { version = "0.4", optional = true }

[dev-dependencies]
async-std = { version = "1.10", features = ["attributes"] }
